# Generated by Django 2.2.6 on 2019-11-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0018_auto_20190816_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagament',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnes.Alumne'),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='sortida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sortides.Sortida'),
        ),
    ]
