# Generated by Django 3.1.2 on 2020-10-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0014_nivell_matricula_oberta'),
        ('sortides', '0022_auto_20200223_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comerç',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=32, unique=True)),
                ('key', models.CharField(max_length=64)),
                ('descripcio', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Comerç',
                'verbose_name_plural': 'Comerços',
            },
        ),
        migrations.CreateModel(
            name='TipusQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipus de quota',
                'verbose_name_plural': 'Tipus de quotes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='QuotaPagament',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sortides.pagament',),
        ),
        migrations.CreateModel(
            name='SortidaPagament',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sortides.pagament',),
        ),
        migrations.AddField(
            model_name='pagament',
            name='dataLimit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagament',
            name='estat',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pagament',
            name='fracciona',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pagament',
            name='importParcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='alumne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.alumne'),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='data_hora_pagament',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='sortida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.sortida'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importQuota', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dataLimit', models.DateField(blank=True, null=True)),
                ('any', models.IntegerField(default=2020)),
                ('descripcio', models.CharField(blank=True, max_length=200)),
                ('comerç', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.comerç')),
                ('curs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.curs')),
                ('tipus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sortides.tipusquota')),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotes',
                'ordering': ['any', 'curs__nom_curs_complert'],
            },
        ),
        migrations.AddField(
            model_name='pagament',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.quota'),
        ),
        migrations.AddField(
            model_name='sortida',
            name='comerç',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.comerç'),
        ),
    ]
