# Generated by Django 3.1.2 on 2021-01-23 20:43

import aula.apps.sortides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20201220_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='any',
            field=models.IntegerField(default=aula.apps.sortides.models.return_any_actual),
        ),
    ]
