# Generated by Django 3.1.2 on 2020-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20201018_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comerç',
            options={'verbose_name': 'TPV', 'verbose_name_plural': 'TPVs'},
        ),
        migrations.AlterField(
            model_name='comerç',
            name='codi',
            field=models.CharField(max_length=32, verbose_name='Codi'),
        ),
        migrations.AlterField(
            model_name='comerç',
            name='descripcio',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom del TPV'),
        ),
        migrations.AlterField(
            model_name='comerç',
            name='key',
            field=models.CharField(max_length=64, verbose_name='Key'),
        ),
    ]
