# Generated by Django 3.1.2 on 2021-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0024_auto_20210123_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='dataLimit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
