# Generated by Django 3.0.6 on 2020-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0030_pagament_estat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagament',
            name='data_hora_pagament',
            field=models.DateTimeField(null=True),
        ),
    ]
