# Generated by Django 3.0.6 on 2020-08-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0014_merge_20200710_0005'),
        ('sortides', '0031_auto_20200716_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='comerç',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.Comerç'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.Curs'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='dataLimit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='tipus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sortides.TipusQuota'),
        ),
    ]
