# Generated by Django 3.1.2 on 2021-01-24 13:46

import aula.apps.sortides.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0032_auto_20200820_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comerç',
            options={'verbose_name': 'TPV', 'verbose_name_plural': 'TPVs'},
        ),
        migrations.AddField(
            model_name='comerç',
            name='entornReal',
            field=models.BooleanField(default=False, verbose_name='Fa servir entorn real'),
        ),
        migrations.AddField(
            model_name='comerç',
            name='nom',
            field=models.CharField(default=None, blank=True, null=True, max_length=32, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comerç',
            name='codi',
            field=models.CharField(max_length=32, verbose_name='Codi Comerç'),
        ),
        migrations.AlterField(
            model_name='comerç',
            name='descripcio',
            field=models.CharField(max_length=200, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='comerç',
            name='key',
            field=models.CharField(max_length=64, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='any',
            field=models.IntegerField(default=aula.apps.sortides.models.return_any_actual),
        ),
        migrations.AlterField(
            model_name='quota',
            name='comerç',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sortides.comerç'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quota',
            name='dataLimit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='descripcio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quota',
            name='tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sortides.tipusquota'),
        ),
    ]
