# Generated by Django 3.1.2 on 2021-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0033_auto_20210124_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='dataLimit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
