# docker/Dockerfile.demo.automatica
FROM python:3.13-slim

WORKDIR /app

# Copiem el codi font
COPY . /app

# Instal·lació de dependències del sistema
RUN apt-get update && apt-get install -y git wait-for-it \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Instal·lació de dependències Python
RUN pip install --upgrade pip && pip install -r requirements.txt

# Collectstatic (opcional)
RUN python manage.py collectstatic --noinput || true

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
