# Generated by Django 3.2.7 on 2021-09-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0010_dadesaddicionalsprofessor_foto'),
        ('presencia', '0008_auto_20191020_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impartir',
            name='professor_guardia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professor_guardia', to='usuaris.professor'),
        ),
        migrations.AlterField(
            model_name='impartir',
            name='professor_passa_llista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professor_passa_llista', to='usuaris.professor'),
        ),
    ]
