# Generated by Django 4.0.2 on 2022-02-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0009_auto_20210911_1741'),
        ('presencia', '0009_controlassistencia_comunicat'),
    ]

    operations = [
    ]
