# Generated by Django 3.2.9 on 2021-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0009_auto_20210911_1741'),
        ('presencia', '0009_controlassistencia_comunicat'),
    ]

    operations = [
    ]
