# Generated by Django 3.1.2 on 2020-12-23 23:50

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnes', '0014_auto_20201223_2350'),
        ('assignatures', '0004_auto_20190922_2001'),
        ('sortides', '0023_auto_20201220_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom alumne')),
                ('cognoms', models.CharField(max_length=100, verbose_name='Cognoms alumne')),
                ('centre_de_procedencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centre de procedència')),
                ('data_naixement', models.DateField(verbose_name='Data de naixement')),
                ('alumne_correu', models.EmailField(help_text="Correu de notificacions de l'alumne", max_length=254, null=True, verbose_name="Correu de l'alumne")),
                ('adreca', models.CharField(max_length=250, verbose_name='Adreça')),
                ('localitat', models.CharField(max_length=250, verbose_name='Localitat')),
                ('cp', models.CharField(max_length=10, verbose_name='Codi postal')),
                ('rp1_nom', models.CharField(max_length=250, verbose_name='Nom complet 1r responsable')),
                ('rp1_telefon1', models.CharField(max_length=15, verbose_name='Telèfon 1r responsable')),
                ('rp1_correu', models.EmailField(max_length=254, verbose_name='Correu 1r responsable')),
                ('rp2_nom', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom complet 2n responsable')),
                ('rp2_telefon1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telèfon 2n responsable')),
                ('rp2_correu', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correu 2n responsable')),
                ('files', private_storage.fields.PrivateFileField(help_text='Documentació obligatòria', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='matricula/%Y/', verbose_name='Fitxer amb documents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('acceptar_condicions', models.BooleanField(verbose_name='Accepto condicions de matrícula')),
                ('curs_complet', models.BooleanField(default=False, help_text='Matrícula típica de totes les UFs', verbose_name='Matrícula del curs complet')),
                ('quantitat_ufs', models.IntegerField(blank=True, default=0, null=True, verbose_name='UFs soltes, curs no complet')),
                ('bonificacio', models.CharField(choices=[('0', 'Cap'), ('5', '50%'), ('1', '100%')], default='0', max_length=1, verbose_name='Tipus de bonificació taxes')),
                ('llistaufs', models.CharField(blank=True, help_text='En cas de UFs soltes', max_length=250, null=True, verbose_name='Mòduls i ufs de la matrícula')),
                ('fracciona_taxes', models.BooleanField(default=False, verbose_name='Fracciona pagament taxes')),
            ],
            options={
                'verbose_name': 'Dades',
                'verbose_name_plural': 'Dades',
            },
        ),
        migrations.CreateModel(
            name='Peticio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumne', models.CharField(help_text="DNI si l'alumne no té RALC", max_length=15, verbose_name="RALC de l'alumne")),
                ('tipusIdent', models.CharField(choices=[('R', 'RALC'), ('D', 'DNI')], default='R', max_length=1, verbose_name="Tipus d'identificació")),
                ('email', models.EmailField(max_length=254, verbose_name='Correu de contacte')),
                ('any', models.IntegerField(default=2020)),
                ('estat', models.CharField(choices=[('P', 'Pendent'), ('R', 'Rebutjada'), ('D', 'Duplicada'), ('A', 'Acceptada'), ('F', 'Finalitzada')], default='P', max_length=1)),
                ('alumne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.alumne')),
                ('curs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnes.curs', verbose_name='Curs on matricular-se')),
                ('dades', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.dades')),
                ('quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.quota')),
            ],
            options={
                'verbose_name': 'Peticio',
                'verbose_name_plural': 'Peticions',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnes.alumne')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assignatures.assignatura')),
            ],
            options={
                'ordering': ['alumne', 'modul', 'numero'],
                'unique_together': {('alumne', 'modul', 'numero')},
            },
        ),
    ]
