# Generated by Django 3.0.6 on 2020-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_auto_20200624_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dades',
            name='bonificacio',
            field=models.CharField(choices=[('0', 'Cap'), ('5', '50%'), ('1', '100%')], default='0', max_length=1, verbose_name='Tipus de bonificació taxes'),
        ),
        migrations.AddField(
            model_name='dades',
            name='curs_complet',
            field=models.BooleanField(default=False, help_text='Matrícula típica de totes les UFs', verbose_name='Matrícula del curs complet'),
        ),
        migrations.AddField(
            model_name='dades',
            name='fracciona_taxes',
            field=models.BooleanField(default=False, verbose_name='Fracciona pagament taxes'),
        ),
        migrations.AddField(
            model_name='dades',
            name='llistaufs',
            field=models.CharField(blank=True, help_text='En cas de UFs soltes', max_length=250, null=True, verbose_name='Mòduls i ufs de la matrícula'),
        ),
        migrations.AddField(
            model_name='dades',
            name='quantitat_ufs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='UFs soltes, curs no complet'),
        ),
    ]
