# Generated by Django 3.1.2 on 2021-01-24 13:46

import aula.apps.sortides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20200820_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticio',
            name='any',
            field=models.IntegerField(default=aula.apps.sortides.models.return_any_actual),
        ),
    ]
