# Generated by Django 3.1.2 on 2020-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0013_alumne_observacions'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivell',
            name='matricula_oberta',
            field=models.BooleanField(default=False),
        ),
    ]
