# Generated by Django 3.1.2 on 2020-12-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20201220_1759'),
        ('alumnes', '0013_alumne_observacions'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivell',
            name='matricula_oberta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nivell',
            name='taxes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.tipusquota'),
        ),
    ]
