# Generated by Django 3.0.6 on 2020-10-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0032_auto_20200820_1700'),
        ('alumnes', '0014_merge_20200710_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivell',
            name='taxes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.TipusQuota'),
        ),
    ]
