# Generated by Django 3.1.2 on 2020-10-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20201018_1301'),
        ('alumnes', '0014_nivell_matricula_oberta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivell',
            name='taxes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.tipusquota'),
        ),
    ]
