# Generated by Django 3.1.2 on 2020-11-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0015_nivell_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivell',
            name='matricula_oberta',
        ),
    ]
